name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
    - 'pam/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'pam/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Remove apt repos that are known to break from time to time 
    # See https://github.com/actions/virtual-environments/issues/323  
    - name: Remove broken apt repos [Ubuntu]
      run: for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
    - name: Update Ubuntu
      run: sudo apt-get update -y; sudo apt-get upgrade -y
    - name: Install Dependencies
      run: cd pam; sudo make install
    - name: make
      run: cd pam; sudo make

