name: C/C++ CI

on:
  push:
    branches: [ github-ci ]
    paths:
    - 'pam/**'
  pull_request:
    branches: [ github-ci ]
    paths:
    - 'pam/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get update; sudo apt-get -y upgrade;cd pam; sudo make install
    - name: make
      run: cd pam; sudo make

